#!/bin/sh
# /usr/local/bin/i3exit

lock() {
    i3lock -i /home/lola/Pictures/lock-screen.png -p default -n -f -e
}

case "$1" in
    lock)
        i3lock -i /home/lola/Pictures/lock-screen.png -p default -n -f -e
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
