# EXPORTS
if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  exec startx
fi

source $HOME/.rvm/scripts/rvm
export ZSH="$HOME/.oh-my-zsh"
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:$HOME/bin:$HOME/.local/bin:/home/angel/anaconda3/bin:$PATH
export PATH="/home/angel/.pyenv/bin:$PATH"
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
#
export TERM=xterm-256color        # for common 256 color terminals (e.g. gnome-terminal)
# export TERM=screen-256color       # for a tmux -2 session (also for screen)
# export TERM=rxvt-unicode-256color # for a colorful rxvt unicode session
# export DIRCOLORTHEME='dircolors.ansi-dark'

ZSH_THEME="powerlevel10k/powerlevel10k"

POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon user dir_writable dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time root_indicator background_jobs time disk_usage ram)
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%(?:%{$fg_bold[magenta]%}\uf7d3 ➜ :%{$fg_bold[red]%}\uf7d3 ➜ )'

#POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_USER_ICON="\uf004" # 
POWERLEVEL9K_ROOT_ICON="\uf21e"
POWERLEVEL9K_SUDO_ICON=$'\uf21e' # 
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
# POWERLEVEL9K_VCS_GIT_ICON='\uF408 '
POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uf1d3'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='red'


ZSH_DISABLE_COMPFIX=true

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

plugins=(
  git
  iterm2
  macports
  man
  osx
  python
  composer
)


# source ~/.bash_profile

if [ -f ~/.bash_profile ]; then
    . ~/.bash_profile;
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory notify
unsetopt beep extendedglob
bindkey -e

zstyle :compinstall filename '/home/angel/.zshrc'

autoload -Uz compinit
compinit

# PROMPT
# PS1='%U%B%n@%m%u:%b%~ - %B%b$(git_super_status)
#  %{%F{red}%}<3%{%F{white}%} '

# Tilix fix
# if missing, need to symlink
# sudo ln -s /etc/profile.d/vte-2.91.sh /etc/profile.d/vte.sh
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
source ~/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme


# source $HOME/.zsh-plugins/zsh-git-prompt/zshrc.sh # Zsh git prompt
# source $ZSH/oh-my-zsh.sh
source $HOME/.aliases
eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
