# EXPORTS
source $HOME/.rvm/scripts/rvm
export ZSH="$HOME/.oh-my-zsh"
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:$HOME/bin:$HOME/.local/bin:/home/angel/anaconda3/bin:$PATH
export PATH="/home/angel/.pyenv/bin:$PATH"
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

export TERM=xterm-256color        # for common 256 color terminals (e.g. gnome-terminal)
export TERM=screen-256color       # for a tmux -2 session (also for screen)
export TERM=rxvt-unicode-256color # for a colorful rxvt unicode session
export DIRCOLORTHEME='dircolors.ansi-dark'

source $HOME/.aliases
# source $HOME/.zsh-plugins/zsh-git-prompt/zshrc.sh # Zsh git prompt
source $ZSH/oh-my-zsh.sh

ZSH_THEME="powerlevel9k/powerlevel9k"

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory notify
unsetopt beep extendedglob
bindkey -e

zstyle :compinstall filename '/home/angel/.zshrc'

autoload -Uz compinit
compinit

# PROMPT
# PS1='%U%B%n@%m%u:%b%~ - %B%b$(git_super_status)
#  %{%F{red}%}<3%{%F{white}%} '

# Tilix fix
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
